import type { Preset } from '../types';
import { q, sf, step, timer, withIds } from './helpers.ts';

const CODE = `async function a() {
  console.log('1: a start');
  await null; // 此行之后，剩余函数体作为微任务入队
  console.log('3: a resumed');
}
a();
queueMicrotask(() => {
  console.log('4: micro');
});
setTimeout(() => {
  console.log('5: timeout');
}, 0);
console.log('2: sync end');`;

// consoleLines 是累计快照：每一步都必须携带截至该步的全部输出
const OUT1 = ['1: a start'];
const OUT2 = [...OUT1, '2: sync end'];
const OUT3 = [...OUT2, '3: a resumed'];
const OUT4 = [...OUT3, '4: micro'];
const OUT5 = [...OUT4, '5: timeout'];

export const presetAwait: Preset = {
	id: 'await',
	title: '进阶 · await 与微任务',
	difficulty: 2,
	code: CODE,
	expectedOutput: OUT5,
	trace: withIds([
		step({
			title: '整个脚本(script)本身就是一个宏任务，先进入宏任务队列',
			phase: 'task',
			macro: [q('script', 'script', 'macro')],
			active: ['macro'],
		}),
		step({
			title: 'script 出队压栈；函数声明已提升，从 a() 开始执行',
			phase: 'task',
			line: 6,
			ev: 'dequeue',
			stack: [sf('script', 'script')],
			active: ['stack', 'code'],
		}),
		step({
			title: 'a() 入栈',
			phase: 'task',
			line: 6,
			ev: 'push',
			stack: [sf('script', 'script'), sf('a', 'a()')],
			active: ['stack', 'code'],
		}),
		step({
			title: "console.log('1: a start') 入栈",
			phase: 'task',
			line: 2,
			ev: 'push',
			stack: [sf('script', 'script'), sf('a', 'a()'), sf('log-1', 'log')],
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 1: a start，log 出栈',
			phase: 'task',
			line: 2,
			ev: 'pop',
			stack: [sf('script', 'script'), sf('a', 'a()')],
			console: OUT1,
			active: ['console'],
		}),
		step({
			title: 'await null：a 让出控制权出栈，剩余函数体作为微任务入队',
			phase: 'task',
			line: 3,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			micro: [q('cb-a', 'a 剩余体', 'micro')],
			console: OUT1,
			active: ['micro', 'stack'],
		}),
		step({
			title: 'queueMicrotask：排在 cb-a 之后（FIFO）',
			phase: 'task',
			line: 7,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT1,
			active: ['code', 'micro'],
		}),
		step({
			title: 'setTimeout 回调交给 Web APIs 计时',
			phase: 'task',
			line: 10,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT1,
			active: ['code', 'webapis'],
		}),
		step({
			title: "console.log('2: sync end') 入栈",
			phase: 'task',
			line: 13,
			ev: 'push',
			stack: [sf('script', 'script'), sf('log-2', 'log')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT1,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 2: sync end',
			phase: 'task',
			line: 13,
			ev: 'pop',
			stack: [sf('script', 'script')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT2,
			active: ['console'],
		}),
		step({
			title: 'script 执行完毕，出栈',
			phase: 'task',
			ev: 'pop',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT2,
			active: ['stack'],
		}),
		step({
			title: '任务结束，检查微任务队列：2 个，逐个清空',
			phase: 'microtask',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-a', 'a 剩余体', 'micro'), q('cb-micro', 'micro 回调', 'micro')],
			console: OUT2,
			active: ['micro'],
		}),
		step({
			title: 'cb-a 出队压栈：从 await 之后继续执行',
			phase: 'microtask',
			line: 4,
			ev: 'dequeue',
			stack: [sf('cb-a', 'a 剩余体')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-micro', 'micro 回调', 'micro')],
			console: OUT2,
			active: ['micro', 'stack', 'code'],
		}),
		step({
			title: "console.log('3: a resumed') 入栈",
			phase: 'microtask',
			line: 4,
			ev: 'push',
			stack: [sf('cb-a', 'a 剩余体'), sf('log-3', 'log')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-micro', 'micro 回调', 'micro')],
			console: OUT2,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 3: a resumed',
			phase: 'microtask',
			line: 4,
			ev: 'pop',
			stack: [sf('cb-a', 'a 剩余体')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-micro', 'micro 回调', 'micro')],
			console: OUT3,
			active: ['console'],
		}),
		step({
			title: 'cb-a 执行完，出栈',
			phase: 'microtask',
			ev: 'pop',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-micro', 'micro 回调', 'micro')],
			console: OUT3,
			active: ['stack'],
		}),
		step({
			title: 'cb-micro 出队压栈',
			phase: 'microtask',
			line: 8,
			ev: 'dequeue',
			stack: [sf('cb-micro', 'micro 回调')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT3,
			active: ['micro', 'stack', 'code'],
		}),
		step({
			title: "console.log('4: micro') 入栈",
			phase: 'microtask',
			line: 8,
			ev: 'push',
			stack: [sf('cb-micro', 'micro 回调'), sf('log-4', 'log')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT3,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 4: micro',
			phase: 'microtask',
			line: 8,
			ev: 'pop',
			stack: [sf('cb-micro', 'micro 回调')],
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT4,
			active: ['console'],
		}),
		step({
			title: 'cb-micro 执行完，出栈',
			phase: 'microtask',
			ev: 'pop',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT4,
			active: ['stack'],
		}),
		step({
			title: '微任务队列已空',
			phase: 'microtask',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT4,
			active: ['micro'],
		}),
		step({
			title: '渲染机会：本例无 rAF，浏览器可能跳过绘制',
			phase: 'render',
			webApis: [timer('cb-timeout', 'timer(0ms)')],
			console: OUT4,
			active: ['render'],
		}),
		step({
			title: 'timer(0ms) 已到点，回调进入宏任务队列',
			phase: 'task',
			line: 10,
			ev: 'enqueue',
			macro: [q('cb-timeout', 'timeout 回调', 'macro')],
			console: OUT4,
			active: ['webapis', 'macro'],
		}),
		step({
			title: '新一轮循环：宏任务出队，压栈',
			phase: 'task',
			line: 11,
			ev: 'dequeue',
			stack: [sf('cb-timeout', 'timeout 回调')],
			console: OUT4,
			active: ['macro', 'stack', 'code'],
		}),
		step({
			title: "console.log('5: timeout') 入栈",
			phase: 'task',
			line: 11,
			ev: 'push',
			stack: [sf('cb-timeout', 'timeout 回调'), sf('log-5', 'log')],
			console: OUT4,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 5: timeout',
			phase: 'task',
			line: 11,
			ev: 'pop',
			stack: [sf('cb-timeout', 'timeout 回调')],
			console: OUT5,
			active: ['console'],
		}),
		step({
			title: '回调执行完，出栈',
			phase: 'task',
			ev: 'pop',
			console: OUT5,
			active: ['stack'],
		}),
		step({
			title: '微任务队列已空，快速通过',
			phase: 'microtask',
			console: OUT5,
			active: ['micro'],
		}),
		step({
			title: '渲染机会：无 rAF，跳过',
			phase: 'render',
			console: OUT5,
			active: ['render'],
		}),
		step({
			title: '队列全空，事件循环空闲——演示结束',
			phase: 'task',
			console: OUT5,
			active: [],
		}),
	]),
};
