import type { Preset } from '../types';
import { q, raf, sf, step, timer, withIds } from './helpers.ts';

const CODE = `console.log('1: sync');
requestAnimationFrame(() => {
  console.log('4: raf');
});
setTimeout(() => {
  console.log('3: timeout');
}, 0);
Promise.resolve().then(() => {
  console.log('2: then');
});`;

// consoleLines 是累计快照：每一步都必须携带截至该步的全部输出
const OUT1 = ['1: sync'];
const OUT2 = [...OUT1, '2: then'];
const OUT3 = [...OUT2, '3: timeout'];
const OUT4 = [...OUT3, '4: raf'];

export const presetRender: Preset = {
	id: 'render',
	title: '综合 · 渲染帧时机',
	difficulty: 3,
	code: CODE,
	expectedOutput: OUT4,
	trace: withIds([
		step({
			title: '整个脚本(script)本身就是一个宏任务，先进入宏任务队列',
			phase: 'task',
			macro: [q('script', 'script', 'macro')],
			active: ['macro'],
		}),
		step({
			title: 'script 出队，压入调用栈开始执行',
			phase: 'task',
			line: 1,
			ev: 'dequeue',
			stack: [sf('script', 'script')],
			active: ['stack', 'code'],
		}),
		step({
			title: "console.log('1: sync') 入栈",
			phase: 'task',
			line: 1,
			ev: 'push',
			stack: [sf('script', 'script'), sf('log-1', 'log')],
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 1: sync，log 出栈',
			phase: 'task',
			line: 1,
			ev: 'pop',
			stack: [sf('script', 'script')],
			console: OUT1,
			active: ['console'],
		}),
		step({
			title: 'rAF 回调交给 Web APIs：挂在渲染时机，不进宏/微队列',
			phase: 'task',
			line: 2,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT1,
			active: ['code', 'webapis'],
		}),
		step({
			title: 'setTimeout 回调交给 Web APIs 计时',
			phase: 'task',
			line: 5,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT1,
			active: ['code', 'webapis'],
		}),
		step({
			title: 'Promise.then：回调进入微任务队列',
			phase: 'task',
			line: 8,
			ev: 'enqueue',
			stack: [sf('script', 'script')],
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-then', 'then 回调', 'micro')],
			console: OUT1,
			active: ['code', 'micro'],
		}),
		step({
			title: 'script 执行完毕，出栈',
			phase: 'task',
			ev: 'pop',
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-then', 'then 回调', 'micro')],
			console: OUT1,
			active: ['stack'],
		}),
		step({
			title: '任务结束，清空微任务队列',
			phase: 'microtask',
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			micro: [q('cb-then', 'then 回调', 'micro')],
			console: OUT1,
			active: ['micro'],
		}),
		step({
			title: 'then 回调出队，压栈执行',
			phase: 'microtask',
			line: 9,
			ev: 'dequeue',
			stack: [sf('cb-then', 'then 回调')],
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT1,
			active: ['micro', 'stack', 'code'],
		}),
		step({
			title: "console.log('2: then') 入栈",
			phase: 'microtask',
			line: 9,
			ev: 'push',
			stack: [sf('cb-then', 'then 回调'), sf('log-2', 'log')],
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT1,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 2: then',
			phase: 'microtask',
			line: 9,
			ev: 'pop',
			stack: [sf('cb-then', 'then 回调')],
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT2,
			active: ['console'],
		}),
		step({
			title: 'then 回调执行完，出栈',
			phase: 'microtask',
			ev: 'pop',
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT2,
			active: ['stack'],
		}),
		step({
			title: '微任务队列已空',
			phase: 'microtask',
			webApis: [raf('cb-raf', 'rAF 回调'), timer('cb-timeout', 'timer(0ms)')],
			console: OUT2,
			active: ['micro'],
		}),
		step({
			title: 'timer(0ms) 已到点，回调进入宏任务队列',
			phase: 'task',
			line: 5,
			ev: 'enqueue',
			webApis: [raf('cb-raf', 'rAF 回调')],
			macro: [q('cb-timeout', 'timeout 回调', 'macro')],
			console: OUT2,
			active: ['webapis', 'macro'],
		}),
		step({
			title: '宏任务出队，压栈',
			phase: 'task',
			line: 6,
			ev: 'dequeue',
			stack: [sf('cb-timeout', 'timeout 回调')],
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT2,
			active: ['macro', 'stack', 'code'],
		}),
		step({
			title: "console.log('3: timeout') 入栈",
			phase: 'task',
			line: 6,
			ev: 'push',
			stack: [sf('cb-timeout', 'timeout 回调'), sf('log-3', 'log')],
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT2,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 3: timeout',
			phase: 'task',
			line: 6,
			ev: 'pop',
			stack: [sf('cb-timeout', 'timeout 回调')],
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT3,
			active: ['console'],
		}),
		step({
			title: '回调执行完，出栈',
			phase: 'task',
			ev: 'pop',
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT3,
			active: ['stack'],
		}),
		step({
			title: '微任务队列已空，快速通过',
			phase: 'microtask',
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT3,
			active: ['micro'],
		}),
		step({
			title: '渲染步骤：绘制前执行 rAF 回调',
			phase: 'render',
			webApis: [raf('cb-raf', 'rAF 回调')],
			console: OUT3,
			active: ['render'],
		}),
		step({
			title: 'rAF 回调进栈执行（注意：不经宏/微任务队列）',
			phase: 'render',
			line: 3,
			ev: 'callback-run',
			stack: [sf('cb-raf', 'rAF 回调')],
			console: OUT3,
			active: ['render', 'stack', 'code'],
		}),
		step({
			title: "console.log('4: raf') 入栈",
			phase: 'render',
			line: 3,
			ev: 'push',
			stack: [sf('cb-raf', 'rAF 回调'), sf('log-4', 'log')],
			console: OUT3,
			active: ['stack', 'code'],
		}),
		step({
			title: '打印 4: raf',
			phase: 'render',
			line: 3,
			ev: 'pop',
			stack: [sf('cb-raf', 'rAF 回调')],
			console: OUT4,
			active: ['console'],
		}),
		step({
			title: 'rAF 回调执行完，出栈',
			phase: 'render',
			ev: 'pop',
			console: OUT4,
			active: ['stack'],
		}),
		step({
			title: 'rAF 回调执行完，浏览器绘制这一帧',
			phase: 'render',
			ev: 'render-frame',
			console: OUT4,
			active: ['render'],
		}),
		step({
			title: '队列全空，事件循环空闲——演示结束',
			phase: 'task',
			console: OUT4,
			active: [],
		}),
	]),
};
